register: true

registry:
  url: http://registry:8080

endpoint:
  port: 9080

healthchecks:
  - type: http
    value: http://localhost:9080/
    interval: 30s
    timeout: 15s
    method: GET
    code: 200

commands:
  - cmd: [ "/opt/ibm/wlp/bin/server", "run", "defaultServer" ]
    on_exit: terminate

log_level: debug
